package com.linky.bookreader.dao.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.linky.bookreader.dao.orm.EbookBean;

import com.linky.bookreader.dao.orm.EbookBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ebookBeanDaoConfig;

    private final EbookBeanDao ebookBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ebookBeanDaoConfig = daoConfigMap.get(EbookBeanDao.class).clone();
        ebookBeanDaoConfig.initIdentityScope(type);

        ebookBeanDao = new EbookBeanDao(ebookBeanDaoConfig, this);

        registerDao(EbookBean.class, ebookBeanDao);
    }
    
    public void clear() {
        ebookBeanDaoConfig.getIdentityScope().clear();
    }

    public EbookBeanDao getEbookBeanDao() {
        return ebookBeanDao;
    }

}
